### PR TITLE
fix: normalize 32-bit slice bounds

### LINKED ISSUE #1679: esp32c3-basic emulator: cl/_testgo/reader hangs and does not auto-exit
### Problem
When running `cl/_testgo/reader` with ESP32-C3 emulator target, the process hangs and does not auto-exit.

### Reproduce
```bash
cd cl/_testgo/reader
llgo run -a -target=esp32c3-basic -emulator .
```

### Actual behavior
QEMU boots and reaches `entry 0x40380000`, then the run does not finish automatically (hang).

### Expected behavior
The case should print expected output (`hello world (0x0,0x0)`) and exit automatically.

### Scope
Observed during ESP32-C3 emulator regression checks for PR #1567.

### PR DESCRIPTION
**Pull request by luoliwoshang**
## Summary
- normalize `low/high/max` to target `int` width in SSA `Slice` before calling runtime helpers
- add ESP serial startup regression output for `int64` string slicing (`slice64 ok`)
- make smoke assertion compare expected output tail by N lines (instead of only the last line)

## Root Cause
On 32-bit targets, passing wider bounds (for example `int64`) directly into runtime slice helpers with `int` semantics can cause incorrect behavior (including hangs/no auto-exit).

## Changes
- `ssa/datastruct.go`
  - in `Builder.Slice`, apply `fitIntSize` to non-nil `low/high/max` before helper calls
- `_demo/embed/test-esp-serial-startup.sh`
  - add `int64` slicing regression output in generated `main`
  - update smoke matcher to validate expected tail lines

## Verification
- `go install ./cmd/llgo`
- `_demo/embed/test-esp-serial-startup.sh`
  - ESP32-C3: pass (tail includes `Hello World` + `slice64 ok`)
  - ESP32: pass for this smoke case with local QEMU installed

Fixes #1679

### CODE REVIEW

File: _demo/embed/test-esp-serial-startup.sh [hunk 1]
```diff
@@ -84,6 +100,14 @@ import "github.com/goplus/lib/c"
 
 func main() {
 	c.Printf(c.Str("Hello World\n"))
+	s := "hello"
+	var idx int64 = 1
```
[the remark this answers is not in the document]
Comment (luoliwoshang) [reply _demo/embed/test-esp-serial-startup.sh]: already change to compare all line bbe037c4d29055fc6814b5a35c87a807410cf70f

File: _demo/embed/test-esp-serial-startup.sh [hunk 2]
```diff
@@ -93,10 +117,10 @@ echo ""
 echo "=== ESP Serial Smoke Tests: Build + Emulator Run ==="
```
Comment (cpunion) [inline _demo/embed/test-esp-serial-startup.sh]: Split test cases and test runner

Comment (luoliwoshang) [reply _demo/embed/test-esp-serial-startup.sh]: done
