### PR TITLE
emb(esp32c3): fix nano float output and add temporary startup regressions

### LINKED ISSUE #1664: esp32c3-basic emulator: float output missing in alias/multiret/struczero/cpkgimp
## Summary

On upstream `main`, running ESP32-C3 emulator cases via:

`llgo run -target esp32c3-basic -emulator <case-dir>`

shows float fields missing in formatted output for several cases.

## Reproduction (from `main`)

1. Checkout `main`.
2. Run cases one by one:
   - `llgo run -target esp32c3-basic -emulator ./cl/_testgo/alias`
   - `llgo run -target esp32c3-basic -emulator ./cl/_testgo/multiret`
   - `llgo run -target esp32c3-basic -emulator ./cl/_testgo/struczero`
   - `llgo run -target esp32c3-basic -emulator ./cl/_testdata/cpkgimp`
3. Compare observed output with expected output below.

## Affected cases (expect vs got)

1. `./cl/_testgo/alias`
   - expect: `+5.000000e+00 +8.000000e+00`
   - got: `` (blank output line)
2. `./cl/_testgo/multiret`
   - expect: `1 +2.000000e+00`
   - got: `1 `
3. `./cl/_testgo/struczero`
   - expect:
     - `0x0 +0.000000e+00 notOk: true`
     - `0x0 +0.000000e+00 true`
   - got:
     - `0x0  notOk: true`
     - `0x0  true`
4. `./cl/_testdata/cpkgimp`
   - expect: `3 +6.280000e+00`
   - got: `3 `

## Suspected cause

`newlib` nano formatted I/O splits float support into weak symbols (e.g. `_printf_float`), so linking `libm` alone is not sufficient to enable `%f/%e` output.

### PR DESCRIPTION
**Pull request by luoliwoshang**
## Summary

- fix ESP32-C3 nano formatted float output by linking `_printf_float` for `esp32c3-basic`
- build and link RISCV `libm` in `newlib-esp32` cross-compile config
- add temporary ESP32-C3 float regression checks to startup CI script for:
  - `./cl/_testgo/alias`
  - `./cl/_testgo/multiret`
  - `./cl/_testgo/struczero`
  - `./cl/_testdata/cpkgimp`

## Notes

- The startup-script regression block is temporary and intentionally documented inline.
- It will be moved to unified `cl` tests in a follow-up ESP32-C3 testing PR, then removed from startup script.

Fixes #1664

## Validation

- `go test ./internal/crosscompile/compile/libc -run 'NewlibESP32|GroupCount|GroupNames|CompilerFlags' -count=1`
- `go test ./internal/crosscompile -run 'Libc|NewlibESP32' -count=1`
- `bash _demo/embed/test_esp32c3_startup.sh`

### CODE REVIEW

File: internal/crosscompile/compile/compile.go [hunk 1]
```diff
@@ -99,8 +99,9 @@ func (g CompileGroup) Compile(
 
 // CompileConfig represents compilation configuration
 type CompileConfig struct {
-	Groups       []CompileGroup
-	ExportCFlags []string
+	Groups        []CompileGroup
+	ExportCFlags  []string
+	ExportLDFlags []string
```
Comment (MeteorsLiu) [inline internal/crosscompile/compile/compile.go]: As far as i'm concered, it should not export any ldflags because this is only a library, it should not have an influence on global linking process.

Comment (luoliwoshang) [reply internal/crosscompile/compile/compile.go]: OK,move this LDFlag to esp32c3-basic.json

File: targets/esp32c3-basic.json [hunk 2]
```diff
@@ -10,6 +10,10 @@
 	"serial": "usb",
 	"rtlib": "compiler-rt",
 	"libc": "newlib-esp32",
+	"ldflags": [
+		"-u",
+		"_printf_float"
```
Comment (MeteorsLiu) [inline targets/esp32c3-basic.json]: `-u=_printf_float` maybe better.

Comment (luoliwoshang) [reply targets/esp32c3-basic.json]: Fixed at https://github.com/goplus/llgo/pull/1665/commits/c7ff4163782285a0d0c761be431c1354f0675417 and `-u=_printf_float` not work, so i replace it to `-undefined=_printf_float`

File: _demo/embed/test_esp32c3_startup.sh
Comment (MeteorsLiu) [inline _demo/embed/test_esp32c3_startup.sh:1]: NOTE: this regression test will be removed after #1549 gets merged.

**Review by MeteorsLiu — APPROVED** [review]

**Review by cpunion — APPROVED** [review]

**Comment by luoliwoshang** [comment]
@xushiwei
