### PR TITLE
os:fix os.Errno 's nil pointer derefer in linux

### LINKED ISSUE #825: Unexpected nil pointer dereference when checking non-existent files  existence on Linux and macOS
Unexpected behavior occurs when using os.Stat() to check if a file exists on both Linux and macOS. Additionally, a nil pointer dereference error occurs when attempting to open a non-existent file using os.Open() on Linux systems.
* os.Stat() behaves unexpectedly on both Linux and macOS, returning an "Unknown error: -1" instead of the expected "no such file or directory" error.
* os.Open() causes a nil pointer dereference on Linux systems, while it behaves correctly on macOS.
```go
package main

import (
    "fmt"
    "os"
    "path/filepath"
)

func main() {
    tempDir := os.TempDir()
    noexist := filepath.Join(tempDir, "noexist.h")
    
    // Check file existence
    if _, err := os.Stat(noexist); err != nil {
        if os.IsNotExist(err) {
            fmt.Println("noexist:", err.Error())
        } else {
            fmt.Println("exist,other err:", err.Error())
        }
    }
    
    // Try to open non-existent file
    if _, err := os.Open(noexist); err != nil {
        if os.IsNotExist(err) {
            fmt.Println("noexist:", err.Error())
        } else {
            fmt.Println("exist,other err:", err.Error())
        }
    }
}
```
#### os.Stat
* on linux
```bash
noexist: stat /tmp/noexist.h: no such file or directory
```
* on macos
```bash
noexist: stat /var/folders/5j/sgtxqmbn1hbdqtgx5kkp6y700000gn/T/noexist.h: no such file or directory
```
#### os.Open
* linux
```bash
noexist: open /tmp/noexist.h: no such file or directory
```
* macos
```bash
noexist: open /var/folders/5j/sgtxqmbn1hbdqtgx5kkp6y700000gn/T/noexist.h: no such file or directory
```
#### os.Stat (All unexpected)
* linux
```bash
exist,other err: stat /tmp/noexist.h: Unknown error -1
```
* macos
```bash
exist,other err: stat /var/folders/5j/sgtxqmbn1hbdqtgx5kkp6y700000gn/T/noexist.h: Unknown error: -1
```
#### os.Open 
* linux
```bash
panic: runtime error: invalid memory address or nil pointer dereference
```
* macos (Expected)
```bash
noexist: open /var/folders/5j/sgtxqmbn1hbdqtgx5kkp6y700000gn/T/noexist.h: No such file or directory
```

### PR DESCRIPTION
**Pull request by luoliwoshang**
fix #825 

The panic was in the use `os.Errno`.
in the generate ir in llgo like this demo.
```llvm
; ModuleID = 'errno'
source_filename = "errno"

@errno = external global i32, align 4

declare i32 @putchar(i32)

define i32 @main() {
entry:
  %0 = load i32, ptr @errno, align 4
  %1 = add i32 %0, 48  ; Convert to ASCII digit (assuming errno is 0-9)
  call i32 @putchar(i32 %1)
  call i32 @putchar(i32 10)  ; Print newline
  ret i32 0
}
```
will cause follow error
```bash
/usr/bin/ld: errno: TLS definition in /lib/aarch64-linux-gnu/libc.so.6 section .tbss mismatches non-TLS reference in demo.o
/usr/bin/ld: /lib/aarch64-linux-gnu/libc.so.6: error adding symbols: bad value
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
we can see the marcos define the errno is actually call the__errno_location. in linux
```c
extern int *__errno_location (void) __THROW __attribute_const__;
# define errno (*__errno_location ())
```
in macos is call __error
```c
extern int * __error(void);
#define errno (*__error())
```
so we need another way to get the errno
```llvm
; ModuleID = 'errno'
source_filename = "errno"

declare i32* @__errno_location()
declare i32 @putchar(i32)

define i32 @main() {
entry:
  %errno_ptr = call i32* @__errno_location()
  %errno_val = load i32, i32* %errno_ptr, align 4
  %ascii_val = add i32 %errno_val, 48  
  call i32 @putchar(i32 %ascii_val)
  call i32 @putchar(i32 10)  
  ret i32 0
}
```
```bash
root@be00d9b1c2c9:~/llgo/chore/_xtool/llcppsymg/oserrno/llvm# llvm-as demo.ll -o demo.bc
root@be00d9b1c2c9:~/llgo/chore/_xtool/llcppsymg/oserrno/llvm# llc -filetype=obj demo.bc -o demo.o
root@be00d9b1c2c9:~/llgo/chore/_xtool/llcppsymg/oserrno/llvm# clang demo.o -o demo
root@be00d9b1c2c9:~/llgo/chore/_xtool/llcppsymg/oserrno/llvm# ./demo
0
```
so,by wrapping the errno macro in a C function, we can obtain the actual errno value through a function call across different platforms.
```c
 #include <errno.h>
 int llgoErrno() { return errno; }
```
```go
//go:linkname Errno C.llgoErrno
func Errno() c.Int
```
#### result
we can get expected result of os.Errno's  use

In this demo, when attempting to open a non-existent file, the program uses os.Error to retrieve the actual reason for the operation failure. This tests whether os.Error() is correctly referenced and functioning. The output showing "No such file or directory" confirms that the errno handling is working as expected across different platforms.

`macos`
```bash
❯ llgo run .
noexist: stat /var/folders/5j/sgtxqmbn1hbdqtgx5kkp6y700000gn/T/noexist.txt: No such file or directory
noexist: open /var/folders/5j/sgtxqmbn1hbdqtgx5kkp6y700000gn/T/noexist.txt: No such file or directory
```
`linux`
```bash
noexist: stat /tmp/noexist.txt: No such file or directory
noexist: open /tmp/noexist.txt: No such file or directory
```

### CODE REVIEW

**Comment by xushiwei** [comment]
please review @visualfc.
If os.Errno has bugs, it means os.Stdout/Stderr also has bugs.

**Comment by luoliwoshang** [comment]
> please review @visualfc. If os.Errno has bugs, it means os.Stdout/Stderr also has bugs.

os.Stdout/Stderr/Stdin works normally both in macos & linux
```go
package main

import (
	"io"
	"fmt"
	"os"
)

func main() {
	fmt.Println("Message 1")
	fmt.Fprintln(os.Stdout, "Message 2")
	fmt.Fprintln(os.Stderr, "Message 3")

	input, err := io.ReadAll(os.Stdin)
    if err != nil {
        fmt.Fprintf(os.Stderr, "Error reading input: %v\n", err)
        return
    }
	fmt.Fprintf(os.Stdout, "You entered:\n%s", input)
}
```
```
root@be00d9b1c2c9:~/llgo/_demo/stdout# echo "Hello, World!" | llgo run demo.go
Message 1
Message 2
Message 3
You entered:
Hello, World!
root@be00d9b1c2c9:~/llgo/_demo/stdout# echo "Hello, World!" | go run demo.go
Message 1
Message 2
Message 3
You entered:
Hello, World!
```

**Comment by luoliwoshang** [comment]
> please review @visualfc. If os.Errno has bugs, it means os.Stdout/Stderr also has bugs.

`/usr/include/stdio.h` 
```c
/* Standard streams.  */
extern FILE *stdin;		/* Standard input stream.  */
extern FILE *stdout;		/* Standard output stream.  */
extern FILE *stderr;		/* Standard error output stream.  */
/* C89/C99 say they're macros.  Make them happy.  */
#define stdin stdin
#define stdout stdout
#define stderr stderr
```

File: c/os/_os/os.c [hunk 1]
```diff
@@ -7,3 +8,5 @@ int llgoClearenv() {
 	}
 	return 0;
 }
+
+int llgoErrno() { return errno; }
```
Comment (visualfc) [inline c/os/_os/os.c]: add line end

Comment (luoliwoshang) [reply c/os/_os/os.c]: added
