### PR TITLE
cl: support //export with different symbol names on embedded targets

### LINKED ISSUE #1378: Proposal: support `//export` export a different symbol name at embed target
## Background

Currently, Go's `//export` directive requires that the export name must match the function name exactly. If they don't match, the compiler will report an error:

```go
//export Add
func xxx(a, b C.int) C.int {
    return a + b
}
```

```
# command-line-arguments
./add.go:5:1: export comment has wrong name "Add", want "xxx"
```

This restriction can be problematic in embedded environments where specific symbol names are required by hardware or firmware specifications.

### Compatibility with TinyGo's Practice

TinyGo, as a Go compiler targeting embedded systems and WebAssembly, has already extended the behavior of the `//export` directive to allow export names that don't match function names:

```go
//export LPSPI2_IRQHandler
func interruptLPSPI2() {
    callHandlers(IRQ_LPSPI2)
}
```

This extension is very useful in embedded development because:

1. **Hardware specifications require specific symbol names**: For example, ARM Cortex-M interrupt vector tables require specific handler names (like `Reset_Handler`, `SysTick_Handler`), which are defined by hardware vendors and cannot be changed.

2. **Maintaining code readability**: It allows using descriptive Go function names (like `interruptLPSPI2`) while exporting hardware-required names (like `LPSPI2_IRQHandler`).

3. **TinyGo ecosystem is established**: Many embedded Go projects rely on this feature, forming certain practice conventions.

TinyGo's implementation directly modifies the behavior of `//export`, which differs from standard Go semantics. For LLGO, we want to:

- **Maintain compatibility with standard Go**: Don't modify the standard behavior of `//export`
- **Provide the same capability**: Support separation of export names from function names

#### Scenario 1: System Tick Interrupt Handler

```go
//export SysTick_Handler
func timer_isr() {
    select {
    case timerCh <- struct{}{}:
    default:
        // The consumer is running behind.
    }
}
```

#### Scenario 2: Peripheral Interrupt Handler

```go
//export LPSPI2_IRQHandler
func interruptLPSPI2() {
    callHandlers(IRQ_LPSPI2)
}
```

These scenarios demonstrate how TinyGo uses the `//export` directive to meet hardware specification requirements for specific symbol names while maintaining Go code readability. need provide the same capability but with clearer semantics.

Solution: expand `//export` 's export ability at embed target , support `//export` export a different symbol name at embed target

### PR DESCRIPTION
**Pull request by luoliwoshang**
## Summary

  Implements support for #1378, allowing `//export` directives to use different symbol names on embedded targets (enabled via `-target`
   flag).

  **Key behavior:**
  - ✅ **Embedded targets** (`-target=esp32`, etc.): Different export names supported
  - ❌ **Standard targets** (no `-target` flag): Different export names panic with error message

  ## Example

  ### ✅ Embedded Target (with `-target=esp32`)

  ```go
  //export LPSPI2_IRQHandler
  func interruptLPSPI2() {
      // Hardware interrupt handler
  }

  Compiles successfully.

  ❌ Standard Target (without -target)

  //export LPSPI2_IRQHandler
  func interruptLPSPI2() {
      // Panics: export comment has wrong name "LPSPI2_IRQHandler"
  }

  ✅ Same Name (works everywhere)

  //export HelloWorld
  func HelloWorld() {
      // Works on all targets
  }

  Changes

  Implementation

  - Add EnableExportRename() to control export rename behavior
  - Update initLinknameByDoc() to handle different export names when enabled
  - Add clear error handling: panic for mismatched names on standard targets

  Tests

  - Unit tests covering enabled/disabled scenarios
  - Demo program with verification script
  - CI integration

  Testing

  # Embedded target - succeeds
  llgo build --target=esp32 .

  # Standard target - panics as expected
  llgo build .

  Fixes #1378

  🤖 Generated with https://claude.com/claude-code

  Co-Authored-By: Claude noreply@anthropic.com

### CODE REVIEW

File: cl/import.go [hunk 1]
```diff
@@ -324,17 +331,24 @@ func (p *context) initLinkname(line string, f func(inPkgName string) (fullName s
 	return noDirective
 }
 
-func (p *context) initLink(line string, prefix int, export bool, f func(inPkgName string) (fullName string, isVar, ok bool)) {
+func (p *context) initLink(line string, prefix int, export bool, f func(inPkgName string, isExport bool) (fullName string, isVar, ok bool)) {
 	text := strings.TrimSpace(line[prefix:])
 	if idx := strings.IndexByte(text, ' '); idx > 0 {
 		inPkgName := text[:idx]
-		if fullName, _, ok := f(inPkgName); ok {
+		if fullName, _, ok := f(inPkgName, export); ok {
```
Comment (visualfc) [inline cl/import.go:331]: 函数 f 不需要 isExport 参数，export 情况可以根据 ok 值和 enableExportRename 来判断处理。

Comment (luoliwoshang) [reply cl/import.go:331]: Done in https://github.com/goplus/llgo/pull/1384/commits/2b0b42d8402f0ff305813ffa8928d11d7f0d0819

**Comment by luoliwoshang** [comment]
@xushiwei

File: internal/build/build.go
Comment (luoliwoshang) [inline internal/build/build.go:1]: only work only at tinygo package
